#!/usr/bin/env php
<?php
try {
    // Maybe this file is used as phar-stub? Let's try!
    Phar::mapPhar('php-cs-fixer.phar');
    require_once 'phar://superfixer.phar/vendor/autoload.php';
} catch (PharException $e) {
    // OK, it's not, let give Composer autoloader a try!
    if (file_exists($a = __DIR__.'/../../autoload.php')) {
        require_once $a;
    } else {
        require_once __DIR__.'/vendor/autoload.php';
    }
}

use Superfixer\Application;

$app = new Application();
$app->run();

